# Size
from gui.colors import GREEN

BLOCK_SIZE = 40
LANE_DISPLACEMENT = 2
WINDOW_WIDTH = 40 * BLOCK_SIZE
WINDOW_HEIGHT = 23 * BLOCK_SIZE
BUFFER = BLOCK_SIZE // 2
MID_LANE = BLOCK_SIZE // 2

LANE_CHANGE_STEPS = 3
CROSSING_LIMIT = 5 * BLOCK_SIZE

LANE_MAX_SPEED = BLOCK_SIZE
CROSSING_MAX_SPEED = BLOCK_SIZE // 2

MINIMAL_SPEED = BLOCK_SIZE // 8

WINNING_SCORE = 100

# GUI Only
TIME_PER_FRAME = 60

FLASH_CYCLE = 240 / TIME_PER_FRAME
HALF_FLASH_CYCLE = 120 / TIME_PER_FRAME 

LANECHANGE_TIME_STEPS = 3
CLAIMTIME = 5

MAX_ACC = BLOCK_SIZE // 4
MAX_DEC = BLOCK_SIZE // 2
JUMP_TIME_STEPS = 1

# lane change
NO_LANE_CHANGE = 0
LEFT_LANE_CHANGE = 1
RIGHT_LANE_CHANGE = -1

MAX_STAGNATION_TIME = 10

N_ACTIONS = 3